language: objective-c
osx_image: xcode8.2
before_install:
- brew install qt5 python3
- pip3 install numpy
- sed -i '' 's/QTDIR = $(QTDIR_$(QT_VERSION))/QTDIR = \/usr\/local\/opt\/qt5/g' xcconfig/targetReleaseNionUILauncher.xcconfig
- sed -i '' 's/PYTHONHOME = $(HOME)\/Developer\/anaconda/PYTHONHOME = \/usr\/local\/opt\/python3\/Frameworks\/Python.framework\/Versions\/3.6/g'
  xcconfig/targetReleaseNionUILauncher.xcconfig
- sed -i '' 's/PYTHON_VERSION_NUMBER = 3.5/PYTHON_VERSION_NUMBER = 3.6/g' xcconfig/targetReleaseNionUILauncher.xcconfig
script: xcodebuild -project NionUILauncher.xcodeproj -target "Nion UI Launcher" -configuration Release

after_success:
  - cd build/Release
  - zip -r NionUILauncher.zip Nion\ UI\ Launcher.app

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: YdOi8HmS7oDk9ILSXlMIBbLUsh857dYIs+8VRavZQH+mhixmR9hHMLnjlGGD0n9Z8q7/ze1zDBkK0SKvs61XFmMEytxNWfqi/IdMqfDja8iA69QfZd/X9jZ1EQFOl2Xo3zrZ5wE7Y6CXdSKrydOqRGJ9I5lPDzxLdqgwuRkYKyv4zsQKwhRPtfgP/jdiz4Att3jxcgp0INEVJ8uYVUK0hvCle9/NQLxoxbRZGerBBPJBwV3PL4lovedfA31eq89ROYQUsV9cSiu7+J8i8FytFYpFpvhOtzuoIdJJmH77LjAe40Q/GFENKsAt6vap9Y6PMVbpflYYiouTnlbLB4hVQzsCm9mlefqWmXQdVYCkeWybWEikvpjyEQoI8TKEPV/pXAbensAbvwdwM+QhMFI9iulBIy4BYpB6Qz9SinY/8eamRmCez961OGahl93htDKo2d5qxMx415u3AT4YrkD5L9gakmWRs5Q0Ty/yKy1g0gO6eMJtpayIgNU2XfYiMHdXflARPYNLu+Z9olrAu9dH3KgNEEXS+EnEPbmjv1T6vMgoPqYEv9SOjfNzw7s6NkQYwfCFd/Cl2N2Dh6MQKE6oJnyjQY9tv0U1d/42UHg5QFFnK1D1ZUcuaQ9Z8mggaMfHJWv5D6M88gUhHeeYNTwNF1ZCozrlI3YohDQuM/W8jgU=
  file: build/Release/NionUILauncher.zip
  on:
    repo: meyer9/nionui-launcher
